//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(schema_name = "public", table_name = "completed_sessions")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub tournament_id: String,
    pub text_id: i32,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub accuracy: Option<Decimal>,
    #[sea_orm(column_type = "Decimal(Some((5, 2)))", nullable)]
    pub wpm: Option<Decimal>,
    pub created_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::texts::Entity",
        from = "Column::TextId",
        to = "super::texts::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Texts,
    #[sea_orm(
        belongs_to = "super::tournaments::Entity",
        from = "Column::TournamentId",
        to = "super::tournaments::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Tournaments,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::texts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Texts.def()
    }
}

impl Related<super::tournaments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tournaments.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
