//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

pub use super::completed_sessions::Entity as CompletedSessions;
pub use super::texts::Entity as Texts;
pub use super::tournaments::Entity as Tournaments;
pub use super::users::Entity as Users;
