//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.7

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
#[serde(untagged)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "tournament_privacy")]
pub enum TournamentPrivacy {
    #[sea_orm(string_value = "open")]
    Open,
    #[sea_orm(string_value = "invitational")]
    Invitational,
}
