name: Trigger auto deployment for app-yuxi-prod

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/app-yuxi-prod-AutoDeployTrigger-327f7fdb-c5eb-4734-8558-0a662b8314df.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APPYUXIPROD_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.APPYUXIPROD_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.APPYUXIPROD_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acryuxiregistrye5150074.azurecr.io
          registryUsername: ${{ secrets.APPYUXIPROD_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.APPYUXIPROD_REGISTRY_PASSWORD }}
          containerAppName: app-yuxi-prod
          resourceGroup: rg-yuxi-prod
          imageToBuild: acryuxiregistrye5150074.azurecr.io/app-yuxi-prod:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


