name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_check: # Renamed job from 'build' for better clarity
    name: Build & Check (ubuntu-latest, ${{ matrix.toolchain }}) # Descriptive name for the matrix job run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Optional: set to true if you want all matrix jobs to cancel on the first failure
      matrix:
        os: [ubuntu-latest] # Simplified to only run on Linux
        # Simplified to 'stable' toolchain. You can add 'beta' back if you still need it: [stable, beta]
        toolchain: [stable]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.toolchain }}
          # Removed rustfmt and clippy from components.
          # llvm-tools-preview is kept; remove it if not strictly needed by your build/check process
          # for a slightly faster toolchain setup.
          components: llvm-tools-preview

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      # Run cargo build and cargo check
      - name: Build and Check
        run: cargo build && cargo check

      # The 'cargo fmt' and 'cargo clippy' steps have been removed to simplify the workflow.